In [3]:
import numpy as np

We store the nodes $X$ and weights $W$ of Gaussian quadrature formula with $5$ nodes. These nodes and weights are rescaled/translated so that they refer to the interval $[0,1]$ instead of the usual $[-1,1]$ where they are deifned,  i.e. so that $$ \int_0^1 f(x)dx \approx \sum_{i=1}^5 w_i f(x_i). $$

In [64]:
def Gauss_Data():
    X = (np.array([-0.9061798459386641,-0.5384693101056831,0,0.5384693101056831,
    0.9061798459386641])+1)/2
    W = 0.5*np.array([0.23692688505618908,0.4786286704993664,128/225,
    0.4786286704993664,0.23692688505618908])
    return X,W

We define the three reference basis functions $\varphi_0$, $\varphi_1$, $\varphi_2$ for $X_h^2$, and their derivatives. 

In [77]:
phi = lambda x: [(x-1)*(2*x-1), 4*(1-x)*x, x*(2*x-1)]
Dphi = lambda x: [4*x-3, 4-8*x, 4*x-1]

Function to assemble the matrices, with "whichOne=Mass" if we want the Mass matrix $M$, and "whichOne=Stiffness" if we want the Stiffness matrix $K$.

In [89]:
def assembleMatrix(whichOne):
    X,W = Gauss_Data()
    res = 0
    
    
    Mat = np.zeros((3,3))
    
    if whichOne == "Mass":
                
        for r in range(3):
            for s in range(3):
                for i in range(0,len(X)):
                    cc = phi(X[i])
                    Mat[r,s] += W[i] * cc[r] * cc[s]
                    
    elif whichOne == "Stiffness":
                
        for r in range(3):
            for s in range(3):
                for i in range(0,len(X)):
                    cc = Dphi(X[i])
                    Mat[r,s] += W[i] * cc[r] * cc[s]
    
    return Mat

In [90]:
M = assembleMatrix("Mass")
K = assembleMatrix("Stiffness")

In [91]:
print(M*30)

[[ 4.  2. -1.]
 [ 2. 16.  2.]
 [-1.  2.  4.]]


In [92]:
print(K*3)

[[ 7. -8.  1.]
 [-8. 16. -8.]
 [ 1. -8.  7.]]
